apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: speedtest-plotter
  name: speedtest-plotter-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500M